sudo: false
language: python

python:
  - "2.7"
  - "nightly"

install:
  - pip install tox

script:
  - tox

notifications:
  email: true

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5